import { z } from 'zod';

const auditFields = {
  schema_version: z.literal('v1').default('v1'),
  source_reference: z.string().default('unknown'),
  reasoning: z.string().default('generated by pipeline'),
  confidence: z.number().min(0).max(1).default(0.5),
  units: z.string().default('unknown'),
  generated_at: z.string().datetime().default(() => new Date().toISOString()),
  pipeline_run_id: z.string().default('unknown'),
};

export const IngestionOutput = z.object({
  ...auditFields,
  lines: z.array(z.record(z.string(), z.unknown())),
  paths: z.array(z.record(z.string(), z.unknown())),
  text: z.array(z.record(z.string(), z.unknown())),
  dimensions: z.array(z.record(z.string(), z.unknown())),
  notes: z.array(z.record(z.string(), z.unknown())),
  annotations: z.array(z.record(z.string(), z.unknown())),
});

export const ScaleDetectionOutput = z.object({
  ...auditFields,
  scale: z.number(),
  method: z.string(),
  detected_text: z.string().nullable(),
  unit_system: z.string(),
});

export const GeometryOutput = z.object({
  ...auditFields,
  walls: z.array(z.record(z.string(), z.unknown())),
  rooms: z.array(z.record(z.string(), z.unknown())),
  openings: z.array(z.record(z.string(), z.unknown())),
  zones: z.array(z.record(z.string(), z.unknown())),
});

export const MeshQualityReportSchema = z.object({
  ...auditFields,
  is_watertight: z.boolean(),
  non_manifold_edge_count: z.number().int(),
  inverted_normal_count: z.number().int(),
  degenerate_face_count: z.number().int(),
  passed: z.boolean(),
  failure_reasons: z.array(z.string()),
});

export const InsulationTakeoffOutput = z.object({
  ...auditFields,
  wallSurfaceArea: z.number(),
  floorCeilingArea: z.number(),
  volume: z.number(),
  insulation: z.record(z.string(), z.unknown()).optional(),
  perWallDetails: z.array(z.record(z.string(), z.unknown())).default([]),
});

export const ExportManifest = z.object({
  ...auditFields,
  jobId: z.string(),
  exports: z.array(
    z.object({
      artifactType: z.enum(['obj', 'step', 'usd']),
      url: z.string(),
      fileSizeBytes: z.number().int(),
      isValid: z.boolean(),
      validationError: z.string().nullable(),
    })
  ),
});

export const JobStatusResponse = z.object({
  ...auditFields,
  jobId: z.string(),
  status: z.string(),
  transitions: z.array(z.object({ status: z.string(), createdAt: z.string().datetime() })),
});

export const schemaRegistry = {
  ingestion: IngestionOutput,
  scale: ScaleDetectionOutput,
  geometry: GeometryOutput,
  mesh_quality: MeshQualityReportSchema,
  insulation_takeoff: InsulationTakeoffOutput,
  export_manifest: ExportManifest,
  job_status: JobStatusResponse,
} as const;

export type SchemaStage = keyof typeof schemaRegistry;
