from datetime import datetime
from typing import Any, Literal
from pydantic import BaseModel, Field


class AuditabilityFields(BaseModel):
    schema_version: Literal["v1"] = "v1"
    source_reference: str = Field(default="unknown")
    reasoning: str = Field(default="generated by pipeline")
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    units: str = Field(default="unknown")
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    pipeline_run_id: str = Field(default="unknown")


class IngestionOutput(AuditabilityFields):
    lines: list[dict[str, Any]]
    paths: list[dict[str, Any]]
    text: list[dict[str, Any]]
    dimensions: list[dict[str, Any]]
    notes: list[dict[str, Any]]
    annotations: list[dict[str, Any]]


class ScaleDetectionOutput(AuditabilityFields):
    scale: float
    method: str
    detected_text: str | None = None
    unit_system: str


class GeometryOutput(AuditabilityFields):
    walls: list[dict[str, Any]]
    rooms: list[dict[str, Any]]
    openings: list[dict[str, Any]]
    zones: list[dict[str, Any]]


class MeshQualityReportSchema(AuditabilityFields):
    is_watertight: bool
    non_manifold_edge_count: int
    inverted_normal_count: int
    degenerate_face_count: int
    passed: bool
    failure_reasons: list[str]


class TakeoffLineItem(BaseModel):
    quantity: float
    unit: str
    geometry_entity_id: str
    source_note: str
    legend_reference: str | None = None
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str


class InsulationTakeoffOutput(AuditabilityFields):
    wallSurfaceArea: float
    floorCeilingArea: float
    volume: float
    line_items: list[TakeoffLineItem]
    review_required: list[TakeoffLineItem] = []


class ExportArtifact(BaseModel):
    artifact_type: Literal["obj", "step", "usd"]
    url: str
    file_size_bytes: int
    is_valid: bool
    validation_error: str | None = None


class ExportManifest(AuditabilityFields):
    job_id: str
    exports: list[ExportArtifact]


class JobStatusTransition(BaseModel):
    status: str
    created_at: datetime


class JobStatusResponse(AuditabilityFields):
    job_id: str
    status: str
    transitions: list[JobStatusTransition]

